apiVersion: v1
appVersion: "1.6.0"
description: Share passwords securely
name: snappass
version: 0.2.1
sources:
  - https://github.com/pinterest/snappass
maintainers:
  - name: Fairfax Media Operations
    email: github@fairfaxmedia.com.au
dependencies:
- name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 17.0.1
